name: "Dragondrop TFState Migration"
description: "Plan or Apply State Migrations"
inputs:
  # TODO: TF Cloud authentication -- Need to figure this out quickly
  aws-access-key-id:
    description: "AWS_ACCESS_KEY_ID that has read/write permissions to the s3 bucket where tfmigrate histories are stored."
    required: false
  aws-secret-access-key:
    description: "AWS_SECRET_ACCESS_KEY that has read/write permissions to the s3 bucket where tfmigrate histories are stored."
    required: false
  google-application-credentials:
    description: "GOOGLE_APPLICATION_CREDENTIALS that have that has read/write permissions to the GCS bucket where tfmigrate histories are stored."
    required: false
  is-apply:
    description: "Boolean representing whether the job should run statemigration or just check to see if they are valid."
    required: true
    default: "false"
  terraform-version:
    description: "Version of terraform to use for running the statemigration."
    required: true
    default: "latest"
  workspace-directories:
    description: "List of relative paths to workspace directories with statemigration to perform."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  build-args:
    TERRAFORM_VERSION: { { inputs.terraform-version } }
  env:
    AWSAccessKeyID: {{ inputs.aws-access-key-id }}
    AWSSecretAccessKey: {{ inputs.aws-secret-access-key }}
    GoogleApplicationCredentials: {{ inputs.google-application-credentials }}
    IsApply: {{ inputs.is-apply }}
    WorkspaceDirectories: {{ inputs.workspace-directories }}
