name: "Dragondrop TFState Migration"
branding:
  icon: cloud
  color: red
description: "Plan or Apply State Migrations"
inputs:
  is-apply:
    description: "Boolean representing whether the job should run statemigration or just check to see if they are valid."
    required: true
    default: "false"
  terraform-cloud-organization:
    description: "Name of the terraform cloud organization containing state information."
    required: true
  terraform-cloud-token:
    description: "Terraform cloud access token corresponding to the Terraform Cloud organization above."
    required: true
  terraform-workspace-sensitive-vars:
    description: "Mapping between workspaces to sensitive variables."
    required: false
  terraform-var-set-sensitive-vars:
    description: "Mapping between variable sets to sensitive variables."
    required: false
  terraform-version:
    description: "Version of terraform to use for running the statemigration. Must only be the numerical version ('1.2.3' is valid, '~>1.2.3' is not)."
    required: false
    default: ""
  workspace-to-directories:
    description: "Map of workspace names to directories with state migration commands to be run."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    TERRAFORMVERSION: ${{ inputs.terraform-version }}
    ISAPPLY: ${{ inputs.is-apply }}
    TERRAFORMCLOUDORGANIZATION: ${{ inputs.terraform-cloud-organization }}
    TERRAFORMCLOUDTOKEN: ${{ inputs.terraform-cloud-token }}
    TERRAFORMWORKSPACESENSITIVEVARS: ${{ inputs.terraform-workspace-sensitive-vars }}
    TERRAFORMVARSETSENSITIVEVARS: ${{ inputs.terraform-var-set-sensitive-vars }}
    WORKSPACETODIRECTORY: ${{ inputs.workspace-to-directories }}
