name: "Dragondrop TFState Migration"
branding:
  icon: cloud
  color: red
description: "Plan or Apply State Migrations"
inputs:
  is-apply:
    description: "Boolean representing whether the job should run statemigration or just check to see if they are valid."
    required: true
    default: "false"
  terraform-cloud-organization:
    description: "Name of the terraform cloud organization containing state information."
    required: true
  terraform-cloud-token:
    description: "Terraform cloud access token corresponding to the Terraform Cloud organization above."
    required: true
  terraform-cloud-variable-name:
    description: "Terraform cloud variable name within Terraform definitions."
    required: false
  terraform-version:
    description: "Version of terraform to use for running the statemigration."
    required: true
    default: "latest"
  workspace-to-directories:
    description: "Map of workspace names to directories with state migration commands to be run."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    TERRAFORM_VERSION: ${{ inputs.terraform-version }}
    ISAPPLY: ${{ inputs.is-apply }}
    TERRAFORMCLOUDORGANIZATION: ${{ inputs.terraform-cloud-organization }}
    TERRAFORMCLOUDTOKEN: ${{ inputs.terraform-cloud-token }}
    TERRAFORMCLOUDVARIABLENAME: ${{ inputs.terraform-cloud-variable-name }}
    WORKSPACETODIRECTORY: ${{ inputs.workspace-to-directories }}
