version: "3.8"

services:
  tfstate-migration:
    build:
      context: .
    environment:
      - "ISAPPLY=false"
      - "TERRAFORMCLOUDTOKEN=$TerraformCloudToken"
      - "TERRAFORMCLOUDORGANIZATION=$TerraformCloudOrganization"
      - "TERRAFORMVARSETSENSITIVEVARS=$TerraformVarSetSensitiveVars"
      - "TERRAFORMVERSION=$TerraformVersion"
      - "TERRAFORMWORKSPACESENSITIVEVARS=$TerraformWorkspaceSensitiveVars"
      - "WORKSPACETODIRECTORY=$WorkspaceToDirectory"
